.travis.yml
=> release(0.1.1): release 0.1.1

.travis.yml, packages/cache/package.json, packages/ggeditor/docs/demo/flow-editor.md, packages/ggeditor/package.json, packages/ggeditor/src/editor/styles/index.less, packages/pikachu/package.json, packages/pikachu/sidebar-nav/sidebar-nav.spec.ts, packages/util/src/other/check.ts, scripts/build/generate-less.js, src/styles.less, src/tsconfig.json
=> fix: ggeditor style

LICENSE, packages/ggeditor/docs/getting-started.md, packages/pikachu/advanced-table/demo/basic.md, packages/pikachu/advanced-table/readme.md, packages/pikachu/query-tabs/demo/basic.md, packages/pikachu/query-tabs/readme.md, packages/pikachu/smart-text/demo/basic.md, packages/pikachu/smart-text/readme.md, packages/pikachu/smart-text/smart-text.component.ts, packages/theme/src/pipes/shortcut/shortcut.pipe.ts
=> complete demo and docment

.travis.yml, _mock/user.ts, packages/acl/package.json, packages/testing/package.json, packages/theme/package.json, packages/theme/src/pipes/currency/cn-currency.pipe.ts, packages/theme/src/pipes/keys/keys.pipe.ts, packages/theme/src/pipes/safe/url.pipe.spec.ts, packages/util/package.json, packages/util/src/validate/validate.spec.ts, src/app/pixelmon.module.ts
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
=> ci: docs site deploy 

.travis.yml
- [x ] The commit message follows our guidelines: https://github.com/1ziton/pixelmon/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[ ] No
```
=> ci: fix publish

CHANGELOG.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(0.1.5): release 0.1.5

_mock/user.ts, packages/pikachu/index.less, packages/pikachu/pagination/demo/basic.md, packages/pikachu/pagination/index.ts, packages/pikachu/pagination/nz-pagination.component.html, packages/pikachu/pagination/nz-pagination.component.ts, packages/pikachu/pagination/nz-pagination.module.ts, packages/pikachu/pagination/nz-pagination.spec.ts, packages/pikachu/pagination/package.json, packages/pikachu/pagination/public-api.ts, packages/pikachu/pagination/readme.md, packages/pikachu/pagination/style/index.less, packages/pikachu/pikachu.module.ts, packages/pikachu/smart-text/readme.md, packages/pikachu/table/demo/basic.md, packages/pikachu/table/readme.md, packages/pikachu/table/style/index.less, packages/pikachu/table/style/variable.less, packages/pikachu/table/table.component.html, packages/pikachu/table/table.component.less, packages/pikachu/table/table.component.ts, packages/pikachu/table/table.module.ts, src/app/app.module.ts, src/app/upload.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: 25
```
[ ] Yes
[x] No
```
=> fix(component:table): fixedPagination

packages/pikachu/public_api.ts, packages/pikachu/query-tabs/demo/basic.md, packages/pikachu/query-tabs/public_api.ts, packages/pikachu/query-tabs/query-tabs-interface.ts, packages/pikachu/query-tabs/query-tabs.component.ts, packages/pikachu/query-tabs/query-tabs.module.ts, packages/pikachu/table/demo/basic.md, packages/pikachu/table/table.component.html, packages/pikachu/table/table.component.less, packages/pikachu/table/table.component.ts, packages/pikachu/upload/public_api.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
=> update fixedPagination demo

README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: update url

.travis.yml, CHANGELOG.md, package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> release(0.1.7): release 0.1.7

packages/pikachu/address-select/address-select.component.ts, packages/pikachu/address-select/address-select.module.ts, packages/pikachu/address-select/address-select.service.ts, packages/pikachu/address-select/demo/basic.md, packages/pikachu/address-select/demo/level-four.md, packages/pikachu/address-select/demo/search.md, packages/pikachu/address-select/interface.ts, packages/pikachu/address-select/p-option-container.component.html, packages/pikachu/address-select/p-option-container.component.ts, packages/pikachu/address-select/p-option.pipe.ts, packages/pikachu/address-select/public_api.ts, packages/pikachu/address-select/readme.md, packages/pikachu/address-select/style/index.less, packages/util/src/other/index.zh-CN.md, packages/util/src/other/other.ts, src/app/shared/services/area.service.ts, tslint.json
close #32 
```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
=> feat(address-select): support search & complete features

packages/pikachu/steps/demo/complex.md, src/app/upload.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(pikachu): assets路径改成绝对路径

packages/pikachu/smart-text/smart-text.component.html, packages/pikachu/table/table.component.html, packages/pikachu/table/table.component.less, packages/pikachu/table/table.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: deprecated
```
```
[ ] Yes
[x] No
```
=> refactor: deprecated usage

CHANGELOG.md, package.json
- [] The commit message follows our guidelines: https://github.com/1ziton/pixelmon/blob/master/CONTRIBUTING.md#commit
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> release(0.1.8): release 0.1.8

CHANGELOG.md, package.json
```
[x] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[ ] No
```
=> release(0.1.9): release 0.1.9

packages/pikachu/table/demo/basic.md, packages/pikachu/table/readme.md, packages/pikachu/table/style/index.less, packages/pikachu/table/table.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(pikachu/table): paginationOffset

packages/pikachu/query-tabs/demo/basic.md, packages/pikachu/table/demo/basic.md, packages/pikachu/table/readme.md, packages/pikachu/table/table.component.html, packages/pikachu/table/table.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
=> refactor(pikachu/table): title

materials/blocks/articles-list/package.json, materials/blocks/entry_components.ts, materials/blocks/readme.md, package.json, src/app/core/materials.service.ts, src/app/core/preloader.ts, src/app/routes/materials/blocks/blocks.component.html, src/app/routes/materials/blocks/blocks.component.less, src/app/routes/materials/blocks/blocks.component.ts, src/app/routes/materials/blocks/materials.json, src/app/routes/materials/materials.module.ts, src/app/routes/materials/preview.component.ts, src/tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(materials): preview blocks demo

_mock/api.ts, materials/blocks/articles-list/package.json, materials/blocks/articles-list/src/articles.component.html, materials/blocks/readme.md, scripts/site/materials/index.ts, src/app/routes/materials/blocks/blocks.component.html, src/app/routes/materials/blocks/blocks.component.ts, src/app/routes/materials/blocks/materials.json, src/app/routes/materials/preview.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: blocks page style

CHANGELOG.md, materials/scaffolds/fml-login/package.json, materials/scaffolds/xzg-login/package.json, package.json, packages/util/src/other/utils.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(0.1.10): release 0.1.10

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(0.2.0): release 0.2.0

packages/pikachu/table/demo/simple.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> site(pikachu/table): simple demo

packages/pikachu/pikachu.module.ts, packages/pikachu/public_api.ts, packages/theme/ng-package.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```
=> build: fix pixelmon-boilerplate build

CHANGELOG.md, package.json
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> release(0.2.1): release 0.2.1

_mock/user.ts, packages/pikachu/query-tabs/query-tabs.component.ts, packages/pikachu/table/demo/basic.md, packages/pikachu/table/demo/simple.md, packages/pikachu/table/readme.md, packages/pikachu/table/table.component.html, packages/pikachu/table/table.component.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(component:table): pageIndex和pageSize支持双向绑定

packages/pikachu/table/style/index.less, packages/pikachu/table/style/variable.less, packages/pikachu/table/table.component.html, packages/pikachu/table/table.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
[ ] Yes
[x] No
```
=> feat(pikachu/table): 默认背景色 & 手动设max-height保证执行

packages/pikachu/index.less, packages/pikachu/input-plus/demo/basic.md, packages/pikachu/input-plus/index.ts, packages/pikachu/input-plus/input-plus.component.html, packages/pikachu/input-plus/input-plus.component.spec.ts, packages/pikachu/input-plus/input-plus.component.ts, packages/pikachu/input-plus/input-plus.module.ts, packages/pikachu/input-plus/package.json, packages/pikachu/input-plus/public_api.ts, packages/pikachu/input-plus/readme.md, packages/pikachu/input-plus/style/index.less, packages/pikachu/input-plus/style/variable.less, packages/pikachu/pikachu.module.ts, packages/pikachu/public_api.ts, packages/theme/styles/variable/pixelmon.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(pikachu): add input-plus component

package.json, packages/pikachu/input-plus/input-plus.component.html, packages/pikachu/input-plus/input-plus.component.spec.ts, packages/pikachu/input-plus/input-plus.module.ts, packages/pikachu/input-plus/style/index.less
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Other... Please describe: Add test case
```
```
[ ] Yes
[x] No
```
=> test(pikachu/input-plus): add test case
